platformName: Android
platformVersion: '7.0'
deviceName: A5RNW18316011440
appPackage: com.tencent.mm
appActivity: .ui.LauncherUI
automationName: Uiautomator2
unicodeKeyboard: true
resetKeyboard: true
noReset: true
chromeOptions:
  androidProcess: com.tencent.mm:tools
---
test_1_ip_api:
  url: http://httpbin.org/ip
  assert:
    ResponseType:
    - type
    - dict
    origin:
    - type
    - str
  method: get
  params: ''
  desc: "\u6D4B\u8BD5httpbin\u7684ip\u63A5\u53E3\u8FD4\u56DE\u6B63\u5E38"
---
name: dashuaihang
---
platformName: Android
platformVersion: '7.0'
deviceName: A5RNW18316011440
appPackage: com.tencent.mm
appActivity: .ui.LauncherUI
automationName: Uiautomator2
unicodeKeyboard: true
resetKeyboard: true
noReset: true
chromeOptions:
  androidProcess: com.tencent.mm:tools
---
- 1
- 2
- 3
- 4
- 5
- 6
--- "\u5929\u884C\u5065\u3002\u541B\u5B50\u4EE5\u81EA\u5F3A\u4E0D\u606F"
---
- 1
- 3
- 4
- 433
- 53
---
str: Hello World!
int: 110
float: 3.141
boolean: true
time: '2016-09-22 03:43:30'
date: '2016-09-22'
platformName: Android
platformVersion: '7.0'
deviceName: A5RNW18316011440
appPackage: com.tencent.mm
appActivity: .ui.LauncherUI
automationName: Uiautomator2
unicodeKeyboard: true
resetKeyboard: true
noReset: true
chromeOptions:
  androidProcess: com.tencent.mm:tools
---
test_1_ip_api:
  url: http://httpbin.org/ip
  assert:
    ResponseType:
    - type
    - dict
    origin:
    - type
    - str
  method: get
  params: ''
  desc: "\u6D4B\u8BD5httpbin\u7684ip\u63A5\u53E3\u8FD4\u56DE\u6B63\u5E38"
---
name: dashuaihang
---
platformName: Android
platformVersion: '7.0'
deviceName: A5RNW18316011440
appPackage: com.tencent.mm
appActivity: .ui.LauncherUI
automationName: Uiautomator2
unicodeKeyboard: true
resetKeyboard: true
noReset: true
chromeOptions:
  androidProcess: com.tencent.mm:tools
---
- 1
- 2
- 3
- 4
- 5
- 6
--- "\u5929\u884C\u5065\u3002\u541B\u5B50\u4EE5\u81EA\u5F3A\u4E0D\u606F"
---
- 1
- 3
- 4
- 433
- 53
---
str: Hello World!
int: 110
float: 3.141
boolean: true
time: '2016-09-22 03:43:30'
date: '2016-09-22'
platformName: Android
platformVersion: '7.0'
deviceName: A5RNW18316011440
appPackage: com.tencent.mm
appActivity: .ui.LauncherUI
automationName: Uiautomator2
unicodeKeyboard: true
resetKeyboard: true
noReset: true
chromeOptions:
  androidProcess: com.tencent.mm:tools
---
test_1_ip_api:
  url: http://httpbin.org/ip
  assert:
    ResponseType:
    - type
    - dict
    origin:
    - type
    - str
  method: get
  params: ''
  desc: "\u6D4B\u8BD5httpbin\u7684ip\u63A5\u53E3\u8FD4\u56DE\u6B63\u5E38"
---
name: dashuaihang
---
platformName: Android
platformVersion: '7.0'
deviceName: A5RNW18316011440
appPackage: com.tencent.mm
appActivity: .ui.LauncherUI
automationName: Uiautomator2
unicodeKeyboard: true
resetKeyboard: true
noReset: true
chromeOptions:
  androidProcess: com.tencent.mm:tools
---
- 1
- 2
- 3
- 4
- 5
- 6
--- "\u5929\u884C\u5065\u3002\u541B\u5B50\u4EE5\u81EA\u5F3A\u4E0D\u606F"
---
- 1
- 3
- 4
- 433
- 53
---
str: Hello World!
int: 110
float: 3.141
boolean: true
time: '2016-09-22 03:43:30'
date: '2016-09-22'
